### ISSUE TITLE
this is a stupid app, since it try to combine tech with politics. shame on you!

### ISSUE THREAD

**Issue by zfdang** [mmastrac/iterm2-zmodem#36]

**Comment by gaofeijin** [comment]
I don't want to be rude, but @mmastrac  you locked my issue, and that is not a friendly gesture. If you truly care about politics in China, you should let us talk and discuss, otherwise what is the difference between you and the goveronment you hate. If you don't want to talk, you should not let politics involved in. I'm always prepared to talk.

**Comment by mmastrac** [comment]
Hi @gaofeijin - you should try searching for "Tiananmen Square" in China to see what results you get before any discussion.
